Create package coach and update README
furgbol/ai pull request #24
Opened 2020-04-04 00:57 UTC by brunolobell

2020-04-07 14:13 UTC, MiguelMDSDP commented on control/coach/half_attack_coach.go
> +)
Bruno, não entendi a funcionalidade dessa constante que tu definiu aqui. Podes me explicar tua linha de pensamento?

2020-04-07 14:16 UTC, MiguelMDSDP commented on control/coach/half_attack_coach.go
> +	Robots := evaluation.word.Team
Aqui tem um problema: tá escrito word. O certo é world.

2020-04-07 14:23 UTC, MiguelMDSDP commented on control/coach/half_attack_coach.go
> +}
Vejo que tu entendeu perfeitamente a funcionalidade da interface. Mas tem alguns problemas na funcionalidade desse tipo em específico: esse index que tu recebe no NewHalfAttack, ele já tá pronto pra ser repassado, então tu não precisa fazer nenhum tratamento. Acompanha a ideia:

Como nesse tipo de coach a gente vai fazer uma pré definição de qual robô (id) é qual posição, ele vai vir com uma estrutura mais ou menos assim:

1. index[1] = "goalkeeper"
2. index[2] = "centerback"
3. index[3] = "striker"

E é exatamente isso que tu precisa repassar, então dentro dessa função GetRoles tu só precisa ter um comando:

return coach.Index

E tá feito.

2020-04-07 14:29 UTC, MiguelMDSDP commented
Mais dois pontos importantes antes do merge:

1. Pode excluir todos as tuas mudanças no pacote parser, deixa só as relacionadas control/coach. Eu tinha cometido um erro na explicação pra vocês da funcionalidade, já expliquei como quero pro Wellington e ele vai atualizar pra nós!
2. Teu PR, mais uma vez, tá com 15 commits. Eu revisei mesmo assim porque não podemos mais atrasar o projeto. Mas não vou fazer mais isso. Treina mais o rebase e tenta entender como ele funciona! Cria um repositório pra teste ou alguma coisa do tipo. Isso tem que estar funcional pra ti.

2020-04-08 13:42 UTC, brunolobell commented on control/coach/half_attack_coach.go
> +)
Eu havia pensado na posição em que cada jogador ficaria, tipo goleiro - no gol, mas acho que é meio óbvio. Logo vou retirar isto.

2020-04-08 14:02 UTC, brunolobell commented on control/coach/half_attack_coach.go
> +}
Eu havia pensado assim, mas desta maneira o "evaluation" (que foi passado por parâmetro) não está sendo usado.

2020-04-08 14:12 UTC, MiguelMDSDP commented on control/coach/half_attack_coach.go
> +}
Não tem problema, o evaluation agora não vai ter muita serventia mesmo. Ele tá sendo implementado porque futuramente vamos usar.

É sempre importante que tu pense só na tua aplicação e como ela vai ser usada, é uma das essências do Clean Architecture. Não pensa no resto do sistema. Ainda não está na hora.

2020-04-08 16:25 UTC, MiguelMDSDP commented on control/coach/half_attack_coach.go
> +	index[3] = "striker"
O index já vem pronto como parâmetro da função, não precisam essas três linhas aqui.

2020-04-08 16:26 UTC, MiguelMDSDP commented on control/coach/half_attack_coach.go
> +	}
Isso aqui já basta dentro desse método, e pode até deixar inline, segundo os padrões do go:
`return &HalfAttackCoah{Index: index}`

2020-04-08 16:27 UTC, MiguelMDSDP requested changes
Só retirar as três linhas indicadas e tá tudo pronto!

2020-04-08 16:45 UTC, MiguelMDSDP approved these changes

2020-04-08 16:45 UTC, merged